apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: najemniski-sos
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: najemniski-sos
    newName: rg.fr-par.scw.cloud/djnd/najemniski-sos
    newTag: 'fe4a35d116c6ac40cf6ea838a9ac79154f14c3ca'
